exclude: '/.idea/|/.vscode/|^docs/|/migrations/'
default_language_version:
  python: python3.13

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0

    hooks:
    - id: check-json
    - id: check-toml
    - id: check-xml
    - id: check-yaml
    - id: debug-statements
    - id: check-builtin-literals
    - id: check-case-conflict
    - id: check-docstring-first
    - id: detect-private-key
    - id: check-symlinks
    - id: check-vcs-permalinks
    - id: check-case-conflict
    - id: check-illegal-windows-names

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.1
    hooks:
      - id: ruff
        name: ruff fix (quiet)
        args: [ "--fix-only" ] # Fix everything that can be fixed, but don't fail.
      - id: ruff
        name: ruff fix (raise)
        args: [ "--fix", ] # Fix everything that can be fixed, and fail if there are any issues.
      - id: ruff-format

